# port = 0 랜덤 포트
server:
  port: 0

spring:
  application:
    name: user-service

# eureka client 등록
# instance-id : 랜덤 포트를 사용하면 eureka 웹에서 서비스가 여러개로 안 보여 따로 세팅해줘야됨
# service-url : 유레카 서버 위치
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname} :${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka